/**
 * PR Agent
 * 生成されたコードをGitHubにコミットしてPRを作成する
 */

import { Octokit } from '@octokit/rest';
import type { GeneratedCode } from './codegen-agent.js';

export class PRAgent {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor(token: string, repository: string) {
    this.octokit = new Octokit({ auth: token });
    const [owner, repo] = repository.split('/');
    this.owner = owner;
    this.repo = repo;
  }

  async createPR(
    issueNumber: number,
    generatedCode: GeneratedCode,
    issueTitle: string
  ): Promise<string> {
    console.log(`📤 Creating PR for issue #${issueNumber}...`);

    // 1. mainブランチの最新コミットを取得
    const { data: ref } = await this.octokit.git.getRef({
      owner: this.owner,
      repo: this.repo,
      ref: 'heads/main',
    });

    const baseSha = ref.object.sha;

    // 2. 新しいブランチを作成
    const branchName = `feature/issue-${issueNumber}-${Date.now()}`;
    await this.octokit.git.createRef({
      owner: this.owner,
      repo: this.repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    console.log(`📝 Created branch: ${branchName}`);

    // 3. ファイルをコミット
    for (const file of generatedCode.files) {
      await this.createOrUpdateFile(branchName, file.path, file.content);
    }

    // 4. PRを作成
    const { data: pr } = await this.octokit.pulls.create({
      owner: this.owner,
      repo: this.repo,
      title: `feat: ${issueTitle}`,
      head: branchName,
      base: 'main',
      body: this.buildPRBody(issueNumber, generatedCode),
      draft: true,
    });

    console.log(`✅ PR created: ${pr.html_url}`);
    return pr.html_url;
  }

  private async createOrUpdateFile(
    branch: string,
    path: string,
    content: string
  ): Promise<void> {
    try {
      // ファイルが存在するか確認
      const { data: existingFile } = await this.octokit.repos.getContent({
        owner: this.owner,
        repo: this.repo,
        path,
        ref: branch,
      });

      // 存在する場合は更新
      if ('sha' in existingFile) {
        await this.octokit.repos.createOrUpdateFileContents({
          owner: this.owner,
          repo: this.repo,
          path,
          message: `chore: Update ${path}`,
          content: Buffer.from(content).toString('base64'),
          branch,
          sha: existingFile.sha,
        });
      }
    } catch (error: any) {
      if (error.status === 404) {
        // ファイルが存在しない場合は新規作成
        await this.octokit.repos.createOrUpdateFileContents({
          owner: this.owner,
          repo: this.repo,
          path,
          message: `feat: Add ${path}`,
          content: Buffer.from(content).toString('base64'),
          branch,
        });
      } else {
        throw error;
      }
    }
  }

  private buildPRBody(issueNumber: number, generatedCode: GeneratedCode): string {
    return `## 🤖 Autonomous Agent Implementation

**Issue**: #${issueNumber}

### Summary
${generatedCode.summary}

### Generated Files
${generatedCode.files.map(f => `- \`${f.path}\``).join('\n')}

### Description
This PR was automatically generated by the Miyabi Autonomous Operations Agent system.

All code has been generated using Claude AI and follows TypeScript best practices with strict mode enabled.

### Checklist
- [x] Code generated by AI
- [x] TypeScript strict mode enabled
- [ ] Manual review required
- [ ] Tests to be added
- [ ] Ready for merge

---

Closes #${issueNumber}

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>`;
  }
}
